version: '2'

services:
    # web server
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 8000:80 # - 80:80      
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/src/static2            

    # gunicorn server
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/vmbloggr/Dockerfile
        entrypoint: /app/docker/vmbloggr/server-entrypoint.sh
        volumes:
            - static_volume:/app/src/static2            
        expose:
            - 8000
        env_file:
          - ./src/.env

    # database
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        env_file:
          - ./src/.env
        expose:
            - 5432
    
volumes:
    static_volume: {}
    log_volume: {}
    postgres_data: {}
